// <auto-generated>
// Rewired Constants
// This list was generated on 5/22/2023 3:35:56 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace Minipede.ReConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Horizontal")]
        public const int Horizontal = 0;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Vertical")]
        public const int Vertical = 1;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Pause")]
        public const int Pause = 3;
        
        // Gameplay
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Fire")]
        public const int Fire = 2;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Inventory")]
        public const int Inventory = 8;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Interact")]
        public const int Interact = 7;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Die")]
        public const int Die = 11;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Eject")]
        public const int Eject = 12;
        
        // UI
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Loadout")]
        public const int Loadout = 10;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Confirm")]
        public const int Confirm = 5;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Cancel")]
        public const int Cancel = 6;
        
    }
    public static partial class Category {
        public const int Default = 0;
        
        public const int Gameplay = 1;
        
        public const int UI = 2;
        
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
            
        }
        public static partial class Keyboard {
            public const int Default = 0;
            
        }
        public static partial class Mouse {
            public const int Default = 0;
            
        }
        public static partial class CustomController {
            public const int Default = 0;
            
        }
    }
    public static partial class MapEnablerRuleSet {
        public const int UI = 0;
        
        public const int Gameplay = 1;
        
    }
}
